### ISSUE TITLE
how can I access the virtual display?

### ISSUE THREAD

**Issue by right-0903** [intel/Display-Virtualization-for-Windows-OS#12]
when I use

```bash
sudo qemu-system-x86_64 \
-m 8192 -enable-kvm -cpu host -smp cores=4,threads=2,sockets=1\
-drive file=win10.qcow2,format=qcow2,cache=none \
-device vfio-pci,host=0000:00:02.1 \
-drive file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
-drive file=win10_VARS.fd,if=pflash,format=raw,unit=1 \
-device virtio-vga,max_outputs=2,blob=true -display gtk,gl=on,full-screen=off \
-object memory-backend-memfd,id=mem1,size=8192M -machine memory-backend=mem1
```

this give me 

```bash
No provider of eglCreateImageKHR found.  Requires one of:
    EGL_KHR_image
    EGL_KHR_image_base
zsh: IOT instruction  sudo qemu-system-x86_64 -m 8192 -enable-kvm -cpu host -smp  -drive  -device
```

then qemu stop. BTW, I use the prebuilt driver from intel.com.

**Comment by downor** [comment]
This error means your host does not have those EGL function at least on the display.
Can you let me know about the host setting, like what 3D driver, OGL/GLES and EGL versions?

**Comment by right-0903** [comment]
> This error means your host does not have those EGL function at least on the display. Can you let me know about the host setting, like what 3D driver, OGL/GLES and EGL versions?

DE: Plasma 5.27.8

WM: kwin_x11 / kwin_wayland

mesa-23.1.7

partial of `eglinfo`

```
GBM platform:
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES 
EGL driver name: iris
OpenGL core profile vendor: Intel
OpenGL core profile renderer: Mesa Intel(R) UHD Graphics (TGL GT1)
OpenGL core profile version: 4.6 (Core Profile) Mesa 23.1.7-1
OpenGL core profile shading language version: 4.60
OpenGL ES profile vendor: Intel
OpenGL ES profile renderer: Mesa Intel(R) UHD Graphics (TGL GT1)
OpenGL ES profile version: OpenGL ES 3.2 Mesa 23.1.7-1
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20
```

[complete glxinfo](https://pastebin.com/SGD3gEVk)
[complete eglinfo](https://pastebin.com/N8mdu7d9)

**Comment by downor** [comment]
You can run any simple rendering app like weston-simple-egl works fine if you run it from the same console where you started QEMU?

**Comment by right-0903** [comment]
> You can run any simple rendering app like weston-simple-egl works fine if you run it from the same console where you started QEMU?

yes, `weston-simple-egl` works fine. BTW, you mean a console? To clarify, I use a laptop, I try to make the vm display show in my internal display.
![Screenshot](https://github.com/intel/Display-Virtualization-for-Windows-OS/assets/111179762/5fbdf3cd-c5a8-45cf-94cb-cc22123d717e)
