### ISSUE TITLE
DVSERVER_HWDCURSOR

### ISSUE THREAD

**Issue by purplepalmdash** [intel/Display-Virtualization-for-Windows-OS#15]
When using  [nomachine](https://www.nomachine.com/)  for desktop remote access, dual cursor(one in host, the other in remote vm) will be displayed like in following image:     
![2023_10_19_22_17_23_885x878](https://github.com/intel/Display-Virtualization-for-Windows-OS/assets/12474582/5f6fa569-ecde-4aef-98fc-207be73d575c)
By enable `DVSERVER_HWDCURSOR` macro in `DVServer/Driver.h` 
```
Line 25: 
//#define DVSERVER_HWDCURSOR
-->
#define DVSERVER_HWDCURSOR

Line 45->Line 58
commet the structure CursorData
```
a compilation error is generated as following:   
    
![2023_10_19_15_30_50_775x519](https://github.com/intel/Display-Virtualization-for-Windows-OS/assets/12474582/834f5c1e-dd97-447c-b671-89525eaab1bd)

By comment `Line 543->Line 547` the build will succeed , using this modified driver the `cursor in vm` disappear.   In most cases the DVServerUMD  works well, but sometimes it will run into `Code 43`(could back to normal by manually disable/enable the DVServerUMD equipment), I doubt this issue related to commented codes, or cause by unsigned driver? 

My question is:    
1. Is it safe for comment `devHandle_cursor` related code?    
2. Is it possible to let `DVSERVER_HWDCURSOR` be a configurable item in vm driver, so the user could choose HWDCURSOR or not---- for example: local use(with cursor in vm) vs remote use (no cursor in vm) ?

**Comment by malayaku** [comment]
DVSERVER_HWDCURSOR is not fully ready for use. Code associated with it will be uncommented and made available for use once it is 100% ready and stable. Hence closing the issue.
