### ISSUE TITLE
"Parameter 'connectors' is unexpected"

### ISSUE THREAD

**Issue by odror** [intel/Display-Virtualization-for-Windows-OS#8]
Using connectors with Display is a very undocumented part of qemu.
I followed your guid and issue the following command
```
sudo qemu-system-x86_64 -m 4096 -enable-kvm -cpu host -smp cores=4,threads=2,sockets=1 -drive file=/var/lib/libvirt/images/win11-3-1.qcow2 -device vfio-pci,host=0000:00:02.7 -device e1000,netdev=net0,mac=DE:AD:BE:EF:1C:00 -netdev tap,id=net0 -device virtio-vga,max_outputs=4,blob=true -display gtk,gl=on,connectors.0=HDMI-A-1,connectors.1=DP-1,connectors.2=DP-2,connectors.3=HDMI-A-2, show-fps=on -object memory-backend-memfd,id=mem1,hugetlb=on,size=4096M -machine memory-backend=mem1
```
I am getting the following error:
```
qemu-system-x86_64: -display gtk,gl=on,connectors.0=HDMI-A-1,connectors.1=DP-1,connectors.2=DP-2,connectors.3=HDMI-A-2,: Parameter 'connectors' is unexpected

```
What am I missing. How Do I pass a monitor to my VM. Connectors does not seem to work.
I have intel i9-13900k CPU and using the latest version of qemu on arch linux.

My Ultimate goal is to used Video acceleration for the display of my VM. I would like to use the UHD 770 GPU with SRIOV With either a passthrough Display or Virtual Display. It is not clear from your guide how to do that.

**Comment by andrewharle** [comment]
@odror - Perhaps a custom build of qemu is required. See [[RFC PATCH 0/9] ui: guest displays multiple connectors suppport and hotplug in](https://patchew.org/QEMU/20230621004355.19920-1-dongwon.kim@intel.com/)

I've not had chance to build and test this myself yet.

**Comment by malayaku** [comment]
For this we need to use customized QEMU version with "connectors" parameter enabled.

https://github.com/intel/iotg-yocto-ese-main/tree/master/recipes-devtools/qemu/qemu
